server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/auth-db}
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:pasanmama5@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:qemj tqaa ecdl dtor}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: OrchidVehicleRentalSecretKeyForJWTTokenGeneration2024SecureKey
  expiration: 86400000

access-control:
  user-manage: OWNER

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
