server:
  port: 8085

spring:
  application:
    name: maintenance-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/maintenance-db}

vehicle:
  service:
    url: ${VEHICLE_SERVICE_URL:http://localhost:8082}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8084}

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}

access-control:
  maintenance-manage: REPAIR_ADVISOR,OWNER
