# Application name
spring.application.name=${APP_NAME:maintenance-service}

# Server port
server.port=${SERVER_PORT:8085}

# MongoDB connection from .env file
spring.data.mongodb.uri=${MONGODB_URI}

# Connection pool settings
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=DEBUG